name: Config Distro
type: module
description: Framework for managing configuration updates from distributions.
core_version_requirement: ^10.3 || ^11
package: Configuration
configure: config_distro.import
dependencies:
  - drupal:config

# Information added by Drupal.org packaging script on 2026-03-26
version: '2.1.0'
project: 'config_distro'
datestamp: 1774547984
